# arxivの学問領域の指定
subject: 'cat:cs.AI OR cat:eess.SP OR cat:stat.ML OR cat:cs.CL OR cat:cs.DB'

# 検索キーワード
keywords:
    deep learning: 3
    natural language: 3
    machine learning: 3
    bayes: 3
    neural network: 1
    regression: 1
    neural: 1
    factorization: 1
    decomposition: 1
    mining: 1
    information extraction: 1
    named entity: 1
    transformer: 1
    classification: 1
    detection: 1
    point process: 1

# 通知の閾値
score_threshold: 0
